cart_view:
    pattern:  /ostoskori
    defaults: { _controller: ShopCartBundle:Cart:view, _locale: fi }
    
cart_add:
    pattern:  /ostoskori/lisaa/{product}
    defaults: { _controller: ShopCartBundle:Cart:add, _locale: fi }
    
cart_remove:
    pattern:  /ostoskori/poista/{product}
    defaults: { _controller: ShopCartBundle:Cart:remove, _locale: fi }
    
cart_edit:
    pattern:  /ostoskori/muokkaa/{product}/kpl/{quantity}
    defaults: { _controller: ShopCartBundle:Cart:edit, _locale: fi }
    
cart_clear:
    pattern:  /ostoskori/tyhjenna
    defaults: { _controller: ShopCartBundle:Cart:clear, _locale: fi }