imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
  dbal:
        driver:   pdo_sqlite
        host:     # Reset
        port:     # Reset
        dbname:   # Reset
        user:     # Reset
        password: # Reset
        path:     "%kernel.root_dir%/cache/test/testdb.sqlite"

  orm:
        auto_generate_proxy_classes: true
        auto_mapping: true