services:
    shop_product.service.tax:
        class:     Shop\ProductBundle\Service\TaxService
        arguments: ["@doctrine.orm.entity_manager"]
        
    shop_product.repository.tax:
        class:           Shop\ProductBundle\Repository\TaxRepository
        arguments:       [Shop\ProductBundle\Entity\Tax]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository