services:
    shop_product.service.product:
        class:     Shop\ProductBundle\Service\ProductService
        arguments: ["@doctrine.orm.entity_manager", "@shop_product.repository.product", "@knp_paginator"]
        
    shop_product.service.category:
        class:     Shop\ProductBundle\Service\CategoryService
        arguments: ["@doctrine.orm.entity_manager", "@shop_product.repository.category"]
        
    shop_product.service.tax:
        class:     Shop\ProductBundle\Service\TaxService
        arguments: ["@doctrine.orm.entity_manager", "@shop_product.repository.tax"]
    
    shop_product.repository.product:
        class:           Shop\ProductBundle\Repository\ProductRepository
        arguments:       [Shop\ProductBundle\Entity\Product]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        
    shop_product.repository.category:
        class:           Shop\ProductBundle\Repository\CategoryRepository
        arguments:       [Shop\ProductBundle\Entity\Category]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
       
    shop_product.repository.tax:
        class:           Shop\ProductBundle\Repository\TaxRepository
        arguments:       [Shop\ProductBundle\Entity\Tax]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        
    money.twig.extension:
        class: Shop\ProductBundle\Twig\Extensions\Extension\Money
        tags:
            -  { name: twig.extension }